name: Android CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APK_NAME: "${{ github.event.repository.name }}.apk"

    steps:
      - uses: actions/checkout@v7
      - name: set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          KEYSTORE: ${{ github.workspace }}/key.jks
          KEY_ALIAS: ${{ vars.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > "$KEYSTORE"
          ./gradlew build
          mv app/build/outputs/apk/release/app-release-unsigned.apk $APK_NAME
      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          path: $APK_NAME
          archive: false